x = input('Digite qualquer coisa:')
print('O tipo primitivo desse valor é', type(x))
print('Só tem letra maiúscula?', x.isupper())
print('Só tem letra minúscula', x.islower())
print('É alfanúmerico?', x.isalnum())
print('É alfabético?', x.isalpha())
print('É um caractere?', x.isascii())
print('É um dígito?', x.isdigit())
print('É um número descimal?', x.isdecimal())
print('Se encaixa nas determinadas regras?', x.isidentifier())
print('É um número?', x.isnumeric())
print('Pode ser impresso?', x.isprintable())
print('É um space?', x.isspace())
print('Começa com a letra maiúscula e termina com minúscula?',  x.istitle())